// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZysaDsmePwwKOfMfJ9frPVOtHRKIGzbQ',
    appId: '1:957280041175:web:5fcd9686ae4c6953139892',
    messagingSenderId: '957280041175',
    projectId: 'crud-4fac0',
    authDomain: 'crud-4fac0.firebaseapp.com',
    storageBucket: 'crud-4fac0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Oc121cj9W8yc0NMCiPmatS3-UN2Q3xg',
    appId: '1:957280041175:android:0e2e5dd37e23c357139892',
    messagingSenderId: '957280041175',
    projectId: 'crud-4fac0',
    storageBucket: 'crud-4fac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlC4Gfe9D00C39DVeHCPigBbkK6R5kpVU',
    appId: '1:957280041175:ios:2bb3f9b80ac34b5a139892',
    messagingSenderId: '957280041175',
    projectId: 'crud-4fac0',
    storageBucket: 'crud-4fac0.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlC4Gfe9D00C39DVeHCPigBbkK6R5kpVU',
    appId: '1:957280041175:ios:f1f5140eae152a04139892',
    messagingSenderId: '957280041175',
    projectId: 'crud-4fac0',
    storageBucket: 'crud-4fac0.appspot.com',
    iosBundleId: 'com.example.crudApp.RunnerTests',
  );
}
